// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"github.com/a8m/ent-sync-example/ent/schema"
	"github.com/a8m/ent-sync-example/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	user.Hooks[1] = userHooks[1]
}

const (
	Version = "v0.9.2-0.20211028115120-dc72d6a2c54f"            // Version of ent codegen.
	Sum     = "h1:Nv8IWhepYfq2SvW8Z1WKtqhE444C2Z4mjjsAjrwZgVc=" // Sum of ent codegen.
)
